11.14. Надо подкачаться
htmlacademy-univer-javascript-1/2432861-kekstagram-4 pull request #12
Opened 2023-12-14 16:17 UTC by MishaZimin

2023-12-15 14:00 UTC, MaksimovG requested changes

2023-12-15 14:00 UTC, MaksimovG commented on index.html
> +          <form class="img-upload__form" id="upload-select-image">
и зачем удалили важные атрибуты тег form? (вопрос риторический, изменения нужно отменить)

2023-12-15 14:00 UTC, MaksimovG commented on js/effect-image.js
> +} from './util.js';
utils.js все таки там не одна утилита

2023-12-15 14:00 UTC, MaksimovG commented on js/error-load-img.js
> +errorButton.addEventListener('click', hideErrorMessage);
нарушение критерия по обработчикам

2023-12-15 14:00 UTC, MaksimovG commented on js/error-load-img.js
> +  removeEventListeners();
как мы видим это функция, а не обработчик

2023-12-15 14:00 UTC, MaksimovG commented on js/succes.js
> +  successButton.addEventListener('click', hideSuccessMessage);
нарушение по обработчикам. У каждого события свой обработчик, который уже будет вызывать функцию

2023-12-17 09:52 UTC, MaksimovG requested changes

2023-12-17 09:52 UTC, MaksimovG commented on js/constants.js
>    sepia: { min: 0, max: 1, step: 0.1 },
форматирование кода,
{
NONE: ...
CHROME: ...
}

2023-12-17 09:52 UTC, MaksimovG commented on js/constants.js
>    none: {},
убрать отсюда

2023-12-17 09:52 UTC, MaksimovG commented on js/constants.js
>    none: {},
Это DEFAULT_SETTING: 'NONE'

2023-12-17 09:52 UTC, MaksimovG commented on js/constants.js
>    heat: { style: 'brightness', unit: '' },
ТОЧНО ТАКЖЕ КАК И НИЖЕ: форматирвоание и CHROME SEPIA и тд

2023-12-17 09:52 UTC, MaksimovG commented on js/effect-image.js
> +  const filterSettings = FilterSetting[currentEffect];
здесь потом можно currentEfferc.toUpperCase() сделать для совместимости с новым оформлением констант

2023-12-17 09:52 UTC, MaksimovG commented on js/effect-image.js
>    if (currentEffect === 'none') {
DEFAULT_EFFECT

2023-12-17 09:52 UTC, MaksimovG commented on js/error-load-img.js
> +// }
Мусор в коде

2023-12-17 09:52 UTC, MaksimovG commented on js/error-load-img.js
> +  document.addEventListener('keydown', handleKeyDown);
названия обработчивов не по критериям

2023-12-17 09:52 UTC, MaksimovG commented on js/success.js
> +  document.addEventListener('keydown', handleKeyDown);
названия обработчиков не соответствуют критериям

2023-12-18 12:49 UTC, MishaZimin reviewed
нужные исправления в коммите "исправления 2"

2023-12-19 18:31 UTC, MaksimovG approved these changes

2023-12-19 18:32 UTC, merged