4.16
htmlacademy-univer-javascript-1/2432861-kekstagram-4 pull request #4
Opened 2023-10-14 16:29 UTC by MishaZimin

2023-10-15 09:14 UTC, MaksimovG requested changes

2023-10-15 09:14 UTC, MaksimovG commented on index.html
> +  <script src="/js/function.js"></script>
где то есть / в начале пути, где-то нет. Нужно везде убрать

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +  const names = ['Александр', 'Екатерина', 'Иван', 'Мария', 'Дмитрий', 'Анна'];
вынести из функции, назвать как коннстанты

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +const generatePhotoId = createRandomIdFromRangeGenerator(1, 25);
1000, 25 - магические числа, вынести в константы

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +const photos = [];
зачем она в  корне файла. Вот именно она как раз должна была быть внутри функции. И возвращалась бы той функцией.

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +
Функция должна была вернуть массив. В файле main.js напишите необходимые функции для создания массива из 25 сгенерированных объектов. Каждый объект массива — описание фотографии, опубликованной пользователем. Функция должна создать массив и вернуть его при вызове

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +// console.log(photos[0].comments);
ненужные комментарии

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +for (let i = 1; i <= 25; i++) {
магическое число 25

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +    likes: getRandomInteger(15, 200),
магические числа 15 и 2000

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +    description: `Описание ${photoId.toString()}-ой фотографии`,
ненужный перевод из числа в строку. Интрполяция (обратные скобки) и так приведут все к строке

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +      // console.error('Перебраны все числа из диапазона от ' + min + ' до ' + max);
ненужный комментарий

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +function getRandomInteger(min, max) {
функция не стрелочная

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +function createRandomIdFromRangeGenerator(min, max) {
функция не срелочная

2023-10-15 09:14 UTC, MaksimovG commented on js/main.js
> +function generateRandomComment() {
функция не стрелочная

2023-10-19 10:34 UTC, MaksimovG requested changes

2023-10-19 10:34 UTC, MaksimovG commented on js/main.js
> +    }
ну вот если у вас это условие выполнится, то функция вернет null. и вы останетесь без случайного числа

2023-10-19 10:34 UTC, MaksimovG commented on js/main.js
> +};
откуда вы все взяли эту 'замечательную' функцию?

2023-10-19 15:36 UTC, MishaZimin commented on js/main.js
> +};
из темы 4.12 Практическая польза замыканий

2023-10-19 15:41 UTC, MishaZimin commented on js/main.js
> +    }
Функция вернет null, только если не может сгенерировать случайное число без повторений. Что нужно выводить в таком случае?

2023-10-19 16:02 UTC, MishaZimin commented on js/main.js
> +};
Видимо я неправильно понял задание, и нужно брать id по порядку

2023-10-20 10:09 UTC, MaksimovG approved these changes

2023-10-21 18:02 UTC, MishaZimin commented
Что делать если кексобот пишет не удалось смержить пулреквест? Я вроде как решил конфликты

2023-10-22 11:40 UTC, MaksimovG approved these changes

2023-10-22 11:40 UTC, merged